# .github/ISSUE_TEMPLATE/config.yml

# æ˜¯å¦å…è®¸åˆ›å»ºå®Œå…¨ç©ºç™½çš„ Issue
blank_issues_enabled: false

# åœ¨ç”¨æˆ·ç‚¹å‡» "New issue" æ—¶æ˜¾ç¤ºçš„å¤–éƒ¨é“¾æ¥
contact_links:
  - name: ğŸ“– é¡¹ç›®æ–‡æ¡£
    url: https://github.com/helian-labs/vuepress-template#readme
    about: è¯·å…ˆæŸ¥é˜…æ–‡æ¡£ï¼Œæ‚¨çš„é—®é¢˜å¯èƒ½å·²ç»æœ‰äº†ç­”æ¡ˆã€‚
  - name: ğŸ’¬ æé—®æˆ–è®¨è®º
    url: https://github.com/helian-labs/vuepress-template/issues
    about: å¦‚æœ‰é—®é¢˜æˆ–æƒ³æ³•éœ€è¦è®¨è®ºï¼Œè¯·åˆ›å»ºä¸€ä¸ªæ–°çš„ Issueã€‚
